Promo-layout
Tsyman/rslang pull request #6
Opened 2020-06-26 14:16 UTC by MariaSyrokvash

Добавляю адаптивную промо-страницу;

2020-06-26 16:07 UTC, drnaida approved these changes

2020-06-27 18:03 UTC, vladboisa commented
Я бы посчитал уместным добавить hover на блоки game__item с поинтер курсором, а в целом отличная работа, молодец)

2020-06-28 17:15 UTC, MariaSyrokvash commented
> Я бы посчитал уместным добавить hover на блоки game__item с поинтер курсором, а в целом отличная работа, молодец)

Согласна, добавила hover. Спасибо)

2020-06-29 12:29 UTC, valeriya-yavorskaya approved these changes
Approved

2020-06-29 12:46 UTC, Student-Java requested changes

2020-06-29 12:46 UTC, Student-Java commented on src/components/pages/stat-page/stat-page.js
> +              <a class="btn promo__link-blue">Сделать первый шаг!</a>
Кнопка налазит на текст
![image](https://user-images.githubusercontent.com/57161516/86006254-12f9c280-b9ec-11ea-903a-18eacb983441.png)

2020-06-29 12:46 UTC, Student-Java commented on src/components/pages/stat-page/stat-page.js
> +              </ul>
Текст на кнопках лучше сделать bold либо еще как-то выделить. Он плохо читаем
![image](https://user-images.githubusercontent.com/57161516/86006534-7daafe00-b9ec-11ea-90a1-f4498c347617.png)

2020-06-29 12:46 UTC, Student-Java commented on src/components/pages/stat-page/stat-page.js
> +              </ul>
Особенно на ярко салатовом

2020-06-29 12:46 UTC, Student-Java commented on src/components/pages/stat-page/stat-page.scss
> +}
двойное `--` в именах лучше не использовать. Если я не ошибаюсь, то это не совсем верно по БЭМ

2020-06-29 13:10 UTC, valeriya-yavorskaya commented on src/components/pages/stat-page/stat-page.scss
> +}
а мне наоборот кажется уместным, это вариант указания модификаторов (сама так пишу=) ). предлагаю вынести это на общее обсуждение

2020-06-29 13:30 UTC, Student-Java commented on src/components/pages/stat-page/stat-page.scss
> +}
Тогда это надо использовать для всех селекторов, так как часть с одиночным - идет. Либо там не модификаторы по задумке

2020-06-29 22:00 UTC, MariaSyrokvash commented on src/components/pages/stat-page/stat-page.js
> +              <a class="btn promo__link-blue">Сделать первый шаг!</a>
У меня все хорошо было, влили стили из другой ветки, где есть свойства по имени тега.
Изменился приоритет (

[https://sun2.beltelecom-by-minsk.userapi.com/A5eFHyH41A1H7LpzSv4GWOrYMo97kgRs7yyV6w/pf9GIGAezg8.jpg](url)

2020-06-30 12:33 UTC, MariaSyrokvash commented on src/components/pages/stat-page/stat-page.js
> +              </ul>
подправила font-size и font-weight

2020-07-02 17:58 UTC, Student-Java commented on src/components/pages/stat-page/stat-page.js
> +              <a class="btn promo__link-blue">Сделать первый шаг!</a>
кнопка по прежнему налазит на текст

2020-07-03 10:57 UTC, vladboisa commented on src/components/pages/stat-page/stat-page.js
> +              <a class="btn promo__link-blue">Сделать первый шаг!</a>
> кнопка по прежнему налазит на текст
Когда смерджим мой пул ПО БЭМ в моей ветке our-team-layout, данный я думаю зарезолвится.

2020-07-03 10:58 UTC, vladboisa approved these changes

2020-07-03 11:04 UTC, Student-Java commented on src/components/pages/stat-page/stat-page.js
> +              <a class="btn promo__link-blue">Сделать первый шаг!</a>
ok

2020-07-03 11:06 UTC, Student-Java approved these changes

2020-07-04 13:18 UTC, valeriya-yavorskaya commented
По коду всё ок, можно мержить

2020-07-04 13:19 UTC, merged