Header-layout
Tsyman/rslang pull request #7
Opened 2020-06-26 14:20 UTC by MariaSyrokvash

1) адаптивный хедер для промо-страницы (stat-page);
2) адаптивный хедер для главной страницы(main-page);

2020-06-26 16:07 UTC, drnaida approved these changes

2020-06-27 16:50 UTC, vladboisa approved these changes

2020-06-29 12:49 UTC, valeriya-yavorskaya requested changes
Нужно поменять ветку, куда пойдёт мерж - не master, а develop. Остальное OK

2020-06-29 12:51 UTC, Student-Java commented on src/components/pages/main-page/main-page.js
> +    this.headerMain = null || document.getElementById('header_container-main');
`null || something` будет всегда возвращать правую часть выражения. В такой записи нет смысла

2020-06-29 12:53 UTC, Student-Java commented on src/components/shared/layout/header/header-main/header-main.js
> +    console.log(this.message);
Все логи для дебага надо убирать перед ПР

2020-06-29 16:20 UTC, valeriya-yavorskaya approved these changes

2020-07-03 10:54 UTC, vladboisa approved these changes

2020-07-04 17:00 UTC, valeriya-yavorskaya commented
По коду всё ок, можно мержить

2020-07-04 18:49 UTC, merged