Authorization page
Tsyman/rslang pull request #8
Opened 2020-06-28 13:59 UTC by Tsyman

Add authorization page in develop branch

2020-06-29 02:19 UTC, Student-Java commented on src/components/pages/authorization-page/tokenHandling/formattedTime.js
> +  const formattedTime = `${hours}:${minutes.substr(-2)}:${seconds.substr(-2)}`;
Есть метод для получения времени из Date: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString

2020-06-29 02:37 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +            <div class="name__inner">
Имени пользователя нет в системе. Даже если бы оно было, то логичнее было бы его запрашивать при регистрации, при логине нужны только почта и пароль

2020-06-29 02:38 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +  }
Зачем нужны эти bind'ы? Я думаю, что без них все должно работать без проблем

2020-06-29 02:44 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +    this.flag = true;
не стоит давать такие имена переменным и полям класса. По такому имени невозможно понять какой функционал несет это поле и приходится лезть в код чтобы это понять. Я бы предложил разделить этот файл на три отдельных: Общий класс родитель, потомок CreateUser, потомок SignIn

2020-06-29 02:47 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +            document.querySelector('.form').reset();
Я думаю, что после успешного логина(как и регистрации нового пользователя) надо закрывать страницу авторизации и переходить на главную страницу

2020-06-29 02:49 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +  async afterRender() {
Мне кажется async у render() и afterRender() лишние. Плюс, модификатор async должен использоваться в связке с await

2020-06-29 03:11 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +  }
Я понял зачем они нужны. Я бы переписал их вызовы в afterRender на стрелочные функции и убрал bind'ы, хотя может в JS и нормально такое делать в конструкторе.

2020-06-29 03:17 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +                localStorage.setItem('token', userName);
Токен затирается именем

2020-06-29 03:21 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +              });
В промисах лучше всегда ставить catch(), если этого не делать, то будут возникать трудноуловимые баги. В данной ситуации, при проблемах с беком, либо ошибке при валидации данных, пользователь не получит вменяемого сообщения

2020-06-29 03:22 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +          }).catch(() => {
Я бы добавил здесь проверку статуса ответа бека, так как ошибки могут быть разные, а сейчас вне зависимости от ошибки будет сообщение о неверном логине и пароле

2020-06-29 03:24 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +            }, 3000);
Строчные литералы, числа и т.д. лучше выносить в константы с говорящими именами и поднимать в самое начало файла. Тогда будет проще вносить изменения в код и читать его

2020-06-29 03:35 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +              .then((data) => {
signInUser() возвращает обычный JS объект, ты же его обрабатываешь как Promise

2020-06-29 03:36 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +          .then((data) => {
выше уже написал про Promise

2020-06-29 03:42 UTC, Student-Java commented on src/components/pages/authorization-page/singInUser.js
> +  localStorage.setItem('tokenEndTime', timestamp(parseJwt(data.token)));
я бы перенес эту строку к остальным строкам которые записывают в стейт токен, айди пользователя.

2020-06-29 03:46 UTC, Student-Java commented on src/components/pages/authorization-page/singInUser.js
> +  localStorage.setItem('tokenEndTime', timestamp(parseJwt(data.token)));
tokenEndTime хранит в себе относительное время в часах-минутах-секундах. Чтобы этим пользоваться надо либо где-то хранить абсолютное время начала сессии пользователя, чтобы высчитывать сколько времени осталось, либо еще как-то извращаться. Я бы оставил время в виде читой Date либо как миллисекунды, тогда гораздо проще будет отслеживать время жизни токена

2020-06-29 03:48 UTC, Student-Java commented on src/components/pages/authorization-page/createUser.js
> +  return data;
На мой взгляд переменная data лишняя, ее можно убрать и просто возвращать результат вызова функции json()

2020-06-29 03:49 UTC, Student-Java commented on src/components/pages/authorization-page/singInUser.js
> +  localStorage.setItem('tokenEndTime', timestamp(parseJwt(data.token)));
плюс после переноса логики в надлежащее ей место singInUser и createUser станут различаться только url и их можно будет объеденить в одну функцию

2020-06-29 03:51 UTC, Student-Java commented on src/components/pages/authorization-page/singInUser.js
> +  const rawResponse = await fetch('https://afternoon-falls-25894.herokuapp.com/signin', {
Обычно адрес бека хранится в файле настроек приложения, чтобы его можно было легко менять (например в зависимости от прод/девелопмент и т.д.)

2020-06-29 03:54 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.scss
> +  transform: rotate(180deg);
В css лучше форматировать свойства по смыслу. Например первыми идут свойства которые влияют на резмеры и позицию элемента, потом шрифты, потом оформление, анимации ...
Такие группы заканчиваются пустой строкой чтобы их было легко визуально идентифицировать

2020-06-29 03:56 UTC, Student-Java commented on src/components/pages/authorization-page/tokenHandling/encodeToken.js
> +function parseJwt(token) {
Имя файла encodeToken, что немного неверно, так как в нем происходит декодирование токена, а не кодирование.

2020-06-29 03:59 UTC, Student-Java commented on src/components/pages/authorization-page/tokenHandling/encodeToken.js
> +function parseJwt(token) {
имя самой функции тоже не совсем отражает суть того что она возвращает. Фактически в ней парсится токен и возвращается один конкретный параметр. Я бы ее назвал иначе, как вариант extractTokenExpiration()

2020-06-29 12:50 UTC, valeriya-yavorskaya requested changes
Нужно поменять ветку, в которую пойдёт мерж - не master, а develop

2020-06-29 13:56 UTC, Tsyman commented on src/components/pages/authorization-page/tokenHandling/formattedTime.js
> +  const formattedTime = `${hours}:${minutes.substr(-2)}:${seconds.substr(-2)}`;
Исправлено

2020-06-29 14:00 UTC, Tsyman commented on src/components/pages/authorization-page/authorization-page.js
> +            <div class="name__inner">
Я сделал это необязательным полем, если пользователь введет имя, то при входе оно его покажет, не введет - не покажет, просто напишет "привет". 
![Безымянный](https://user-images.githubusercontent.com/57630795/86015140-de0c6080-ba29-11ea-9cf1-f4eb2b19ffe6.jpg)

2020-06-29 14:03 UTC, Tsyman commented on src/components/pages/authorization-page/authorization-page.js
> +    this.flag = true;
Я в начале, так и хотел сделать, но не разобрался в наследовании и сделал одним большим классом. Буду разбираться и возможно исправлю.

2020-06-29 14:06 UTC, Tsyman commented on src/components/pages/authorization-page/authorization-page.js
> +            document.querySelector('.form').reset();
Да, оно должно переходить на страницу показанную на картинке снизу, насколько я понимаю, но данная страница еще не сделана.
![Безымянный](https://user-images.githubusercontent.com/57630795/86015900-d4372d00-ba2a-11ea-8f39-f75451185c9a.jpg)

2020-06-29 14:07 UTC, Tsyman commented on src/components/pages/authorization-page/authorization-page.js
> +  async afterRender() {
Исправил

2020-06-29 14:08 UTC, Tsyman commented on src/components/pages/authorization-page/authorization-page.js
> +                localStorage.setItem('token', userName);
Исправил

2020-06-29 14:11 UTC, Tsyman commented on src/components/pages/authorization-page/authorization-page.js
> +              });
Куда лучше всего выводить возникающие ошибки?

2020-06-29 14:14 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +            <div class="name__inner">
ok, просто оно вводится только при регистрации, а при простом логине его уже нет возможности задать

2020-06-29 14:15 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +            document.querySelector('.form').reset();
ок

2020-06-29 14:42 UTC, Tsyman commented on src/components/pages/authorization-page/authorization-page.js
> +          }).catch(() => {
Как узнать статус ошибки ? catch((e) => e.status || e.name || e.message || e.response)

2020-06-29 14:58 UTC, Tsyman commented on src/components/pages/authorization-page/singInUser.js
> +  localStorage.setItem('tokenEndTime', timestamp(parseJwt(data.token)));
Исправил

2020-06-29 14:59 UTC, Tsyman commented on src/components/pages/authorization-page/authorization-page.js
> +              .then((data) => {
Не совсем понял

2020-06-29 14:59 UTC, Tsyman commented on src/components/pages/authorization-page/singInUser.js
> +  localStorage.setItem('tokenEndTime', timestamp(parseJwt(data.token)));
Да я уже потом понял что неправильно считаю время, и сделал просто Date

2020-06-29 15:02 UTC, Tsyman commented on src/components/pages/authorization-page/createUser.js
> +  return data;
Исправил

2020-06-29 15:04 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +          }).catch(() => {
я не правильно написал - статус респонса можно только в then() увидеть, если попали  в catch(), то вообще не ушел запрос на сервер, либо было выброшено исключение в then()
Я бы предложил в then() добавить проверку на 500-е ошибки, на 408-ю

2020-06-29 15:09 UTC, Tsyman commented on src/components/pages/authorization-page/singInUser.js
> +  const rawResponse = await fetch('https://afternoon-falls-25894.herokuapp.com/signin', {
Да, насколько я знаю в .env файле хранится адрес и потом импортится.

2020-06-29 15:09 UTC, Tsyman commented on src/components/pages/authorization-page/authorization-page.scss
> +  transform: rotate(180deg);
Хорошо, учту

2020-06-29 15:11 UTC, Tsyman commented on src/components/pages/authorization-page/tokenHandling/encodeToken.js
> +function parseJwt(token) {
Исправил

2020-06-29 15:12 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +              .then((data) => {
не обращай внимания - это я протупил

2020-06-29 15:13 UTC, Tsyman commented on src/components/pages/authorization-page/authorization-page.js
> +            <div class="name__inner">
Ну вообще да, можно и с бэка тянуть, завтра можно обсудить

2020-06-29 15:15 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +                localStorage.setItem('userID', data.userId);
Наглядный пример почему такие вещи как имена ключей стоит выносить в константы - у тебя здесь `userID`, а на пару строк ниже `userId`

2020-06-29 15:17 UTC, Tsyman commented on src/components/pages/authorization-page/authorization-page.js
> +            }, 3000);
Ok

2020-06-29 15:23 UTC, Tsyman commented on src/components/pages/authorization-page/authorization-page.js
> +                localStorage.setItem('userID', data.userId);
Согласен, исправил. Я не сразу понял в чем ошибка)

2020-06-29 15:25 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +                localStorage.setItem('userID', data.userId);
такие баги тяжело отлавливать когда они вылазят, очень много времени может на них уходить

2020-06-29 16:08 UTC, valeriya-yavorskaya commented on src/components/pages/authorization-page/authorization-page.js
> +  }
нормально; можно поменять на стрелочные функции, дело вкуса

2020-06-29 16:09 UTC, valeriya-yavorskaya approved these changes

2020-07-02 17:40 UTC, Student-Java commented on src/components/pages/authorization-page/authorization-page.js
> +            <div class="name__inner">
Добавлена возможность сохранять/получать имя пользователя

2020-07-02 17:49 UTC, Student-Java commented on src/components/pages/authorization-page/singInUser.js
> +  const rawResponse = await fetch('https://afternoon-falls-25894.herokuapp.com/signin', {
.env файл для бека, на фронте делают файл `config.js`/`settings.js`/`common.js` для хранения общих настроек

2020-07-03 16:08 UTC, drnaida approved these changes

2020-07-03 16:33 UTC, vladboisa approved these changes

2020-07-05 09:36 UTC, valeriya-yavorskaya commented
По коду всё ок, можно мержить

2020-07-05 15:22 UTC, merged